version: '3'

services:
  network:
    build:
      context: .
      dockerfile: ./network/Dockerfile
    ports:
      - 3000:3000 
    restart: on-failure
  peer1:
    build:
      context: .
      dockerfile: ./peer/Dockerfile
    environment:
      - port=8081
    ports:
      - 8081:8080 
    depends_on:
      - network
  peer2:
    build:
      context: .
      dockerfile: ./peer/Dockerfile
    environment:
      - port=8082
    ports:
      - 8082:8080 
    depends_on:
      - network